# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2023 Dell Inc, or its subsidiaries.
---
version: '3.7'

services:
  frr-left:
    image: quay.io/frrouting/frr:8.5.0
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
      - CAP_NET_RAW
    stdin_open: true
    tty: true
    volumes:
      - ./conf:/etc/frr
      - /var/run
    networks:
      internet:
        ipv4_address: 192.168.200.210
      intranet:
        ipv4_address: 10.1.0.2
    command: './charon'

  frr-right:
    image: quay.io/frrouting/frr:8.5.0
    depends_on:
      - frr-left
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
      - CAP_NET_RAW
    stdin_open: true
    tty: true
    volumes:
      - ./conf:/etc/frr
      - /var/run
    networks:
      internet:
        ipv4_address: 192.168.200.200
    command: './charon'

  opi-evpn-server:
    build:
      context: .
    depends_on:
      - frr-left
    volumes_from:
      - frr-left
    networks:
      - internet
      - intranet
    command: /opi-evpn-bridge -port=50151
    healthcheck:
      test: grpcurl -plaintext localhost:50151 list || exit 1

  opi-test:
    image: ghcr.io/opiproject/godpu:main@sha256:8baff1ae55a29a03499474717c25812fbe54225daf137f13230d1c2dea16fe3d
    network_mode: service:frr-left
    depends_on:
      opi-evpn-server:
        condition: service_healthy
    command: test --addr=opi-evpn-server:50151 --pingaddr=10.3.0.1


networks:
  internet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
  intranet:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
